apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trivy-operator-web-ui-operator.name" . }}-env
  labels:
    {{- include "trivy-operator-web-ui-operator.labels" . | nindent 4 }}
data:
  PORTAL_USERNAME: {{ .Values.operator.portal.username | b64enc | required ".Values.operator.portal.username is required !" }}
  PORTAL_PASSWORD: {{ .Values.operator.portal.password | b64enc | required ".Values.operator.portal.username is required !" }}