apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trivy-operator-web-ui-operator.name" . }}-env
  labels:
    {{- include "trivy-operator-web-ui-operator.labels" . | nindent 4 }}
data:
  USERNAME: {{ .Values.operator.username | b64enc | required ".Values.operator.username is required !" }}
  PASSWORD: {{ .Values.operator.password | b64enc | required ".Values.operator.password is required !" }}