apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trivy-operator-web-ui-operator.name" . }}
  labels:
    {{- include "trivy-operator-web-ui-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.operator.serviceAccount.automount }}