common:
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts: []
      # - chart-example.local
    tls: []
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local

  httpRoute:
    enabled: false
    annotations: {}
    parentRefs:
    - name: gateway
      sectionName: http
    hostnames:
      # - chart-example.local

operator:
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: ""

  serviceAccount:
    automount: true
    annotations: {}

  resources:
    requests:
      cpu: 10m
    limits:
      memory: 100Mi

  portal:
    username: ""
    password: ""

  log:
    level: "error"

  livenessProbe:
    httpGet:
      path: /api/health
      port: http

  readinessProbe:
    httpGet:
      path: /api/health
      port: http
  
  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 3000

  service:
    type: ClusterIP
    port: 8080

  url: ""

  httpRoute:
    filters: []
    # - type: RequestHeaderModifier
    #   requestHeaderModifier:
    #     set:
    #     - name: My-Overwrite-Header
    #       value: this-is-the-only-value
    #     remove:
    #     - User-Agent

frontend:
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: ""

  replicaCount: 1

  serviceAccount:
    automount: true
    annotations: {}

  resources:
    requests:
      cpu: 10m
    limits:
      memory: 100Mi
  
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}

  service:
    type: ClusterIP
    port: 8080

  httpRoute:
    filters: []
    # - type: RequestHeaderModifier
    #   requestHeaderModifier:
    #     set:
    #     - name: My-Overwrite-Header
    #       value: this-is-the-only-value
    #     remove:
    #     - User-Agent