common:
  ingress:
    enabled: false
    className: ""
    annotations: {}

    # -- List of hosts for the Ingress.
    hosts: []
      # - chart-example.local

    # -- TLS Section of the Ingress ressource. Keep in mind that each host should have a match in this section in order for the application to fully work. See "TLS" section of the README.
    tls: []
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local

  httpRoute:
    enabled: false
    annotations: {}
    parentRefs:
    - name: gateway
      sectionName: http
    hostnames:
      # -- List of hosts for the HttpRoute.
      # - chart-example.local

operator:
  image:
    repository: "ghcr.io/trivy-operator-web-ui/operator"
    pullPolicy: IfNotPresent
    tag: "0.4.0"

  serviceAccount:
    automount: true
    annotations: {}

  resources:
    requests:
      cpu: 10m
    limits:
      memory: 100Mi

  # -- Username for authentication. The same one to use on the frontend login page.
  username: ""
  # -- Password for authentication. The same one to use on the frontend login page.
  password: ""

  log:
    # -- Log Level for the rust application. Must be one of `debug`, `info`, `warn`, `error`
    level: "error"

  livenessProbe:
    httpGet:
      path: /api/health
      port: http

  readinessProbe:
    httpGet:
      path: /api/health
      port: http
  
  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 3000

  service:
    type: ClusterIP
    port: 8080

  # -- URL of the backend injected in the frontend container. Not considered if either Ingress or HttpRoute is enabled. See "Exposure and URLs" section of the README.
  url: ""


  httpRoute:
    # -- HttpRoute filters for the Operator.
    filters: []
    # - type: RequestHeaderModifier
    #   requestHeaderModifier:
    #     set:
    #     - name: My-Overwrite-Header
    #       value: this-is-the-only-value
    #     remove:
    #     - User-Agent

frontend:
  image:
    repository: "ghcr.io/trivy-operator-web-ui/frontend"
    pullPolicy: IfNotPresent
    tag: "0.1.3"

  replicaCount: 1

  serviceAccount:
    automount: true
    annotations: {}

  resources:
    requests:
      cpu: 10m
    limits:
      memory: 100Mi
  
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  nodeSelector: {}
  tolerations: []
  affinity: {}

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}

  service:
    type: ClusterIP
    port: 8080

  securityContext:
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    runAsUser: 101

  httpRoute:
    # -- HttpRoute filters for the Operator
    filters: []
    # - type: RequestHeaderModifier
    #   requestHeaderModifier:
    #     set:
    #     - name: My-Overwrite-Header
    #       value: this-is-the-only-value
    #     remove:
    #     - User-Agent